### ISSUE TITLE
Support for Django >= 3.2

### ISSUE THREAD

**Issue by ghassanmas** [codingjoe/django-dynamic-filenames#10]
Thank you for your work @codingjoe , 

This library is used by the opend edx platform, and as part of the upgrade process of Django 3.2, this pacakge is flagged as needed maintaince to make sure it support 3.2, for context please refer to  https://github.com/edx/upgrades/issues/74 . 
So that being said, this issue about makiing this library explicity supporting Django 3.2, by adding extra tests which cover Django 3.2

**Comment by codingjoe** [comment]
Good point, @ghassanmas. This package does need some love. Thanks for the PR, I will look into it as soon as possible. Best, Joe

**Comment by ghassanmas** [comment]
@codingjoe 
Thank you for your update, much appreciated. 
I have just raised a new issue I faced when running tests, check #13, happy to push a fix as what you see best fit
