### ISSUE TITLE
Test fails when slugify is installed via python-slugify

### ISSUE THREAD

**Issue by ghassanmas** [codingjoe/django-dynamic-filenames#13]
So when trying to importing `slugify` here: 

https://github.com/codingjoe/django-dynamic-filenames/blob/33763f460deb37233e36985d44fc93af6d4bfd55/dynamic_filenames.py#L9-L10

The importing would as well succeed even though if `slugify` is installed via `python-slugify` instead of `unicode-slugify`. 
Because both libraries are using the same package name, hence mozilla/unicode-slugify/issues/27. 
This would make `slugify` through the following error: 
`TypeError: slugify() got an unexpected keyword argument 'only_ascii'`

I guess to resolve we would need either to 
1. Check if `slugify` is installed via `unicode-slugify`. 
To my knowledge this can be tricky, one solution I came out with, is given `unicode-slugify` comes with `unidecode` function, we can try to import as 
`from slugify import slugify as _slugify,unidecode`
And if slugify doesn't have `unidecode` it will through `ImportError` which is already handeled.
And we can delete the `unidecode` method afterward if succeed. 
2. Use `slugify` always from  `django.utils.text`. 
I guess this would be straightforward to do

Last note,  it seems the mozila version of slugify  `unicode-slugify` doesn't seems to be maintained, also given that solution 1 might break if _`python-slugify` decided in the future to create a method/function with the same name_! 

So I guess, the question is, does the tradeoff of adding complexity to handle this naming conflict is sufficient, instead of implementing solution 2.

**Comment by codingjoe** [comment]
Hi @ghassanmas,

Thank you for reaching out again. I do understand the problem, but I don't think it should be solved in this package. This conflict needs to be resolved by those packages. Our setup config specifies the correct dependencies and your ticket now serves as a googleable documentation, should anyone experience the same error.

I would wait and see about how those packages resolve their naming conflict. I hope that OK with you.

Best,
Joe

**Comment by ghassanmas** [comment]
Hey @codingjoe 
Thank you for the quick response, much appreciated. 

You are right, that this problem should **ideally** be resolved outside the scope of this library. 

Regarding the optional requirement, which is also how it's stated in the Readme.md 
> pip install django-dynamic-filenames[slugify]

Installing it like this will resolve the issue if `python-slugify` was installed before installing this library. 
However if for some reason `python-slugify` is installed **after** this library, then python run time will pick the **latest**  `slugify` package which would be in this case `python-slugify`. 

So it's like gambling which `slugify` is installed lastly. 

I think at least if you are going to wait for this to be resolved, it's just worth mentioning or warning about this case in the Readme.

**Comment by codingjoe** [comment]
Yes, I agree, good documentation is key. I'd really welcome it, if you'd come up with a PR to add the note.
