### ISSUE TITLE
Add date/datetime Field names support

### ISSUE THREAD

**Issue by fabiocaccamo** [codingjoe/django-dynamic-filenames#8]
`yy` -> 2019
`yymm` -> 201904
`yymmdd` -> 20190405
and so on...

**Comment by codingjoe** [comment]
Hi @fabiocaccamo,

good point, that is already possible using Django's built-in `__mod__` syntax not the format syntax provided by this package.

Seealso: https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.FileField.upload_to

Please let me know if you have further questions, or I can can improve the documentation to help other people with a similar question.

Best
-Joe

**Comment by fabiocaccamo** [comment]
@codingjoe 
thanks for the quick reply.

Is it possible to combine the Django's built-in syntax with the format syntax provided by this package?

**Comment by codingjoe** [comment]
Yes, it is. Just throw them all into one string. This package will only fill in the parts it knows. The other parts will be filled by Django.
